services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: chat_app_db
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  mongo_data:
  postgres_data:


